name: ipycytoscape
channels:
  - conda-forge
dependencies:
  - ipycytoscape>=1.0.3
  - jupyterlab=3
  - matplotlib-base
  - networkx
  - pandas
  - traitlets
  - spectate
  - pip
  - pip:
    - py2neo
